services:
  - type: web
    name: ai-backend
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.ai_project_management.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.ai_project_management.settings
