# Generated by Django 5.2 on 2025-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_project_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
